<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;

class PageTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Page::Create([
            'name'                                  => 'Terms & Condition',
            'slug'                                  => 'terms-and-condition',
            'excerpt'                               => 'Terms & Condition',
            'description'                           => '<p style="text-align:center"><span style="font-size:26pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Terms and Conditions</strong></span></span></span></p>

            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Introduction</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Xparts Africa Limited (&quot;we&quot;) operates an e-commerce platform consisting of a website and mobile application (&quot;marketplace&quot;), together with supporting logistics and payment infrastructure, for the sale and purchase of everything car parts in Nigeria (&quot;territory&quot;).</span></span></span></p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">These general terms and conditions shall apply to buyers and sellers on the marketplace and shall govern your use of the marketplace and related services.</span></span></span></p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">By using our marketplace, you accept these general terms and conditions in full. If you disagree with these general terms and conditions or any part of these general terms and conditions, you must not use our marketplace.</span></span></span></p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">If you use our marketplace in the course of a business or other organizational project, then by so doing you:</span></span></span></p>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">confirm that you have obtained the necessary authority to agree to these general terms and conditions;</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">bind both yourself and the person, company, or other legal entity that operates that business or organizational project to these general terms and conditions; and</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">agree that &quot;you&quot; in these general terms and conditions shall reference both the individual user and the relevant person, company, or legal entity unless the context requires otherwise.</span></span></span></li>
            </ol>
            
            <h2><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Customer Service</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">This document is an electronic record in terms of the National Information Technology Development Agency Act, 2007 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the National Information Technology Development Agency Act, 2007. This electronic record is generated by a computer system and does not require any physical or digital signatures.</span></span></span></p>
            
            <p style="text-align:justify">&nbsp;</p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Your use of the Xparts.africa website www.xparts.africa (hereinafter referred to as &quot;Xparts Africa&quot;) and tools are governed by the following terms and conditions as applicable to Xparts.africa. If you transact on Xparts.africa, you shall be subject to the policies that are applicable to the website for such transactions. By mere use of the website, you shall be contracting with Xparts Africa Limited, a company </span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"><span style="background-color:#ffff00">incorporated under Companies and Allied Matters Act, 2004 with head office at 113 Ladipo street, Mushin, Lagos, Nigeria,</span></span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"> and these terms and conditions constitute your binding obligations.</span></span></span></p>
            
            <p style="text-align:justify">&nbsp;</p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">For the purpose of these terms of use, wherever the context so requires, &lsquo;You&rsquo; shall mean any natural or legal person who has agreed to become a member of the Website by providing Registration Data while registering on the Website as a Registered User.</span></span></span></p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">When you use any of the services provided by Xparts.africa, including but not limited to, (e.g., Customer Reviews), you will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. Xparts.africa reserves the right, at its sole discretion, to change, modify, add or remove portions of these Terms of Use at any time. It is your responsibility to check these Terms of Use periodically for changes. Your continued use of the Site following the posting of changes will mean that you accept and agree to the changes. As long as you comply with these Terms of Use, Xparts Africa Limited grants you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Site.</span></span></span></p>
            
            <p style="text-align:justify">&nbsp;</p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"><span style="background-color:#93c47d">ACCESSING, BROWSING, OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS IN THIS AGREEMENT, SO PLEASE READ THIS AGREEMENT CAREFULLY BEFORE PROCEEDING</span></span></span></span></p>
            
            <p style="text-align:justify">&nbsp;</p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Registration and account</strong></span></span></span></h2>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You may not register with our marketplace if you are under 18 years of age (by using our marketplace or agreeing to these general terms and conditions, you warrant and represent to us that you are at least 18 years of age).</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You may register for an account with our marketplace by completing and submitting the registration form on our marketplace.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You represent and warrant that all information provided in the registration form is complete and accurate.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">If you register for an account with our marketplace, you will be asked to provide an email address/user ID and password, and you agree to:</span></span></span>
                <ul>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">keep your password confidential;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">notify us in writing immediately (using our contact details provided) if you become aware of any disclosure of your password; and</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Be responsible for any activity on our marketplace arising out of any failure to keep your password confidential, and that you may be held liable for any losses arising out of such a failure.</span></span></span></li>
                </ul>
                </li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Your account shall be used exclusively by you, and you shall not transfer your account to any third party. If you authorize any third party to manage your account on your behalf, this shall be at your own risk.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We may suspend or cancel your account and/or edit your account details at any time in our sole discretion and without notice or explanation, providing that if we cancel any products or services, you have paid for but not received. You have not breached these general terms and conditions, we will refund you in respect of the same.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You may cancel your account on our marketplace by contacting us as provided.</span></span></span></li>
            </ol>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Terms and conditions of sale</strong></span></span></span></h2>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You acknowledge and agree that:</span></span></span>
            
                <ul>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">the marketplace provides an online location for sellers to sell and buyers to purchase car parts products;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">we shall accept binding sales on behalf of sellers, but Xparts Africa is not a party to the transaction between the seller and the buyer; and</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">a contract for the sale and purchase of a car part or parts will come into force between the buyer and seller. Accordingly, you commit to buying or selling the relevant car part or parts, upon the buyer&rsquo;s confirmation of the purchase via the marketplace.</span></span></span></li>
                </ul>
                </li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Subject to these general terms and conditions, the seller&rsquo;s business terms shall govern the contract for sale and purchase between the buyer and the seller. Notwithstanding this, the following provisions will be incorporated into the contract of sale and purchase between the buyer and the seller:</span></span></span>
                <ul>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">the price for a car part will be as stated in the relevant product listing;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">the price for the car part must include all taxes and comply with applicable laws in force from time to time;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"><span style="background-color:#ffff00">delivery charges, packaging charges, handling charges, administrative charges, insurance costs, other ancillary costs, and charges, will only be payable by the buyer if this is expressly and clearly stated in the product listing;</span></span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">car parts must be of satisfactory quality, fit and safe for any purpose specified in, and conform in all material respects to, the product listing and any other description of the products supplied or made available by the seller to the buyer; and</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">the seller warrants that the seller has good title to, and is the sole legal and beneficial owner of, the products, and that the products are not subject to any third party rights or restrictions including in respect of third party intellectual property rights and/or any criminal, insolvency or tax investigation or proceedings</span></span></span></li>
                </ul>
                </li>
            </ol>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Returns and refunds</strong></span></span></span></h2>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"><span style="background-color:#ffff00">Returns of products by buyers and acceptance of returned products by sellers shall be managed by us</span></span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"> in accordance with the returns page on the marketplace, as may be amended from time to time. Acceptance of returns shall be in our discretion, subject to compliance with applicable laws of the territory</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Refunds in respect of returned products shall be managed in accordance with the refunds page on the marketplace as may be amended from time to time. Our rules on refunds shall be exercised at our discretion, subject to applicable laws of the territory. We may offer refunds, at our discretion:</span></span></span>
                <ul>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">in respect of the product price;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">local and/or international shipping fees (as stated on the refunds page); and</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">by way of store credits, wallet refunds, vouchers, mobile money transfer, bank transfers, or such other method as we may determine from time to time.</span></span></span></li>
                </ul>
                </li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Returned products shall be accepted and refunds issued by Xparts Africa, for and on behalf of the seller.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Changes to our returns page or refunds page shall be effective in respect of all purchases made from the date of publication of the change on our website.</span></span></span></li>
            </ol>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Payment</strong></span></span></span><br />
            <span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">While availing any of the payment method(s) offered at Xparts.africa, Xparts.africa will not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to you due to:</span></span></span></h2>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Lack of authorization for any transaction(s), or</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Exceeding the preset limit mutually agreed by you and between your &quot;Bank(s),&rdquo; or</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Any payment issues arising out of the transaction, or</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">The decline of transaction for any other reason/s.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"><span style="background-color:#ffff00">All payments made against the purchases/services on Xparts.africa by you shall be compulsorily in Nigerian Naira acceptable by the Central Bank of Nigeria.</span></span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"> Xparts.africa does not accept any other form of currency with respect to the purchases made on Xparts Africa.</span></span></span></li>
            </ol>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Breach</strong></span></span></span><br />
            <span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Without limiting other remedies, Xparts.africa may limit your activity, immediately remove your information, warn other Users of your actions, immediately temporarily/indefinitely suspend or terminate or block your membership, and/or refuse to provide you with access to Xparts.africa website in the event, but not limited to:</span></span></span></h2>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">If you breach the Terms of Use or Privacy Policy or other rules and policies, if any;</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">If Xparts.africa is unable to verify or authenticate any information you provide; or</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">If it is believed that your actions may cause legal liability for you, other Users, or Xparts.africa.</span></span></span><br />
                <span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Xparts.africa may at any time at its sole discretion reinstate suspended users. A User that has been suspended or blocked may not register or attempt to register with Xparts.africa or use Xparts.africa Website in any manner whatsoever until such time that such User is reinstated by Xparts.africa. Notwithstanding the foregoing if you breach the Terms of Use or Privacy Policy or other rules and policies, Xparts.africa reserves the right to recover any amounts due and owing by you to Xparts.africa and to take strict legal action including but not limited to a referral to the appropriate law enforcement or other authorities for initiating criminal or other proceedings against you.</span></span></span></li>
            </ol>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Indemnity</strong></span></span></span><br />
            <span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You shall indemnify and hold harmless Xparts.africa its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including attorneys&#39; fees, made by you or any third party or penalty imposed due to or arising out of your use of the goods or services, or in the event you breach this Terms of Use, the Privacy Policy, and other Policies, or your violation of any law, rules or regulations or the rights of a third party on Xparts.africa</span></span></span></h2>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Applicable Law</strong></span></span></span><br />
            <span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">This Agreement shall be governed by and interpreted, and construed in accordance with the laws of The Federal Republic of Nigeria. </span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"><span style="background-color:#ffff00">The place of jurisdiction shall be exclusively in Lagos, Nigeria.</span></span></span></span></h2>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Jurisdictional Issues/Sale in Nigeria Only</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Unless otherwise specified, the material on Xparts.africa is presented solely for the purpose of sale in Nigeria. Xparts Africa makes no representation that materials/services in Xparts.africa are appropriate or available for use in locations/Countries other than Nigeria. Those who choose to access this site from other locations/Countries other than Nigeria do so on their own initiative, and Xparts Africa is not responsible for the supply of goods/availability of services, a refund for the goods or services ordered from other locations/Countries other than Nigeria, compliance with local laws, if and to the extent local laws are applicable.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Trademark, Copyright, and Restriction</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">This site is controlled and operated by Xparts Africa Limited. All material on this site, including images, illustrations, audio clips, and video clips, is protected by copyrights, trademarks, and other intellectual property rights that are owned and controlled by other parties that have licensed their material to us or by us. The materials on the Xparts.africa website owned, operated, licensed, or maintained by us are solely for your personal, non-commercial use. You must not copy, reproduce, republish, upload, post, transmit or distribute such material in any way, including by e-mail or other electronic means and whether directly or indirectly. You must not assist any other person in doing so. Without the prior written consent of the owner, modification of the materials, use of the materials on any other website or networked computer environment, or use of the materials for any purpose other than personal, noncommercial use is a violation of the copyrights, trademarks, and other proprietary rights, and is prohibited. Any use for which you receive any remuneration, whether in money or otherwise, is a commercial use for the purposes of this clause.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Copyright complaint</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We at Xparts Africa respect the intellectual property of others. In case you feel that your work has been copied in a way that constitutes copyright infringement, you can write to us at </span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"><span style="background-color:#ffff00">help@xparts.africa</span></span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Risk of loss</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"><span style="background-color:#ffff00">All items purchased from Xparts.africa are made pursuant to a shipment contract.</span></span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"> This means that the Risk of Loss shall remain with Xparts Africa until the item is transferred to You. In the event that the items are damaged after receipt, the risk falls on the customer.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Product and Service Description</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Xparts.africa tries to be as accurate as possible. However, Xparts.africa does not warrant that product or service description or other content of this site is accurate, complete, reliable, current, or error-free. If a product or service offered on Xparts.africa itself is not as described, your sole remedy is to return it in unused condition.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Pricing and Typographical error</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">If Xparts.africa comes across any difference in pricing resulting from typographic errors with regards to pricing or product/service information, Xparts.africa shall have the right to rectify the same or cancel the order(s) and refund monies, if any, collected from the customer </span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"><span style="background-color:#ffff00">within 10-15 business days of such corrective action taken. The mode of refund will be the same as at the time of placing the order. Cash on Delivery order refunds will be done by cheque.</span></span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Cancellation of order</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Xparts.africa reserves the right to cancel any order without any explanation for doing so, under a situation where Xparts.africa is not able to meet the requirement of the order placed or order so placed/canceled does not comply with the Xparts.africa policy or for any reason. However, Xparts.africa will ensure that any communication of cancellation of an order is intimated within appropriate time to the concerned person, and any applicable refund. will be made in a reasonable time.</span></span></span><br />
            <span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Note that in the event of cancellation of a &lsquo;pay on delivery order, Xparts Africa will not be liable in any form where the customer proceeds to receive orders following an earlier cancellation.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Termination of Service</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Xparts.africa reserves the absolute right to modify, discontinue, temporarily or permanently, any and all portions of our goods and services with or without prior communications. You hereby consent that Xparts.africa will under no circumstance be liable to you or any third party for any modification or discontinuance of the availability of goods or services on the website.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Rules about your content</strong></span></span></span></h2>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">In these general terms and conditions, &quot;your content&quot; means:</span></span></span>
            
                <ul>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">all works and materials (including without limitation text, graphics, images, audio material, video material, audio-visual material, scripts, software, and files) that you submit to us or our marketplace for storage or publication, processing by, or onward transmission; and</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">all communications on the marketplace, including product reviews, feedback, and comments.</span></span></span></li>
                </ul>
                </li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Your content, and the use of your content by us in accordance with these general terms and conditions, must be accurate, complete, and truthful.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Your content must be appropriate, civil, and tasteful, and accord with generally accepted standards of etiquette and behavior on the internet, and must not:</span></span></span>
                <ul>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">be offensive, obscene, indecent, pornographic, lewd, suggestive, or sexually explicit;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">depict violence in an explicit, graphic, or gratuitous manner; or</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">be blasphemous, in breach of racial or religious hatred or discrimination legislation;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">be deceptive, fraudulent, threatening, abusive, harassing, anti-social, menacing, hateful, discriminatory, or inflammatory;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">cause annoyance, inconvenience, or needless anxiety to any person; or</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">constitute spam.</span></span></span></li>
                </ul>
                </li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Your content must not be illegal or unlawful, infringe any person&#39;s legal rights, or be capable of giving rise to legal action against any person (in each case in any jurisdiction and under any applicable law). Your content must not infringe or breach:</span></span></span>
                <ul>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">any copyright, moral right, database right, trademark right, design right, right in passing off or another intellectual property right;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">any right of confidence, right of privacy, or right under data protection legislation;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">any contractual obligation owed to any person; or</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">any court order</span></span></span></li>
                </ul>
                </li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You must not use our marketplace to link to any website or web page consisting of or containing material that would, were it posted on our marketplace, breach the provisions of these general terms and conditions</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You must not submit to our marketplace any material that has ever been the subject of any threatened or actual legal proceedings or other similar complaints.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"><span style="background-color:#ffff00">The review function on the marketplace</span></span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"> may be used to facilitate buyer reviews on products. You shall not use the review function or any other form of communication to provide inaccurate, inauthentic, or fake reviews.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You must not interfere with a transaction by (i) contacting another user to buy or sell an item listed on the marketplace outside of the marketplace; or (ii) communicating with a user involved in an active or completed transaction to warn them away from a particular buyer, seller or item; or (iii) contacting another user with the intent to collect any payments.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You acknowledge that all marketplace users are solely responsible for interactions with other users, and you shall exercise caution and good judgment in your communication with users. You shall not send them personal information, including credit card details.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We may periodically review your content, and we reserve the right to remove any content at our discretion for any reason whatsoever.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Suppose you learn of any unlawful material or activity on our marketplace or any material or activity that breaches these general terms and conditions. In that case, you may inform us by contacting us as provided.</span></span></span></li>
            </ol>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Our rights to use your content</strong></span></span></span></h2>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You grant us a worldwide, irrevocable, non-exclusive, royalty-free license to use, reproduce, store, adapt, publish, translate and distribute your content across our marketing channels and any existing or future media.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You grant us the right to sub-license the rights licensed.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You grant us the right to bring an action for infringement of the rights licensed.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You hereby waive all your moral rights in your content to the maximum extent permitted by applicable law; you warrant and represent that all other moral rights in your content have been waived to the maximum extent permitted by applicable law.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Without prejudice to our other rights under these general terms and conditions, if you breach our rules on content in any way, or if we reasonably suspect that you have breached our rules on content, we may delete, unpublish or edit any or all of your content.</span></span></span></li>
            </ol>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Use of the website and mobile applications</strong></span></span></span></h2>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">In this section, words, &quot;marketplace&quot; and &quot;website&quot; shall be used interchangeably to refer to Xparts.africa&rsquo;s mobile applications and websites.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You may:</span></span></span>
                <ul>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">view pages from our website in a web browser;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">download pages from our website for caching in a web browser;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">print pages from our website for your own personal and noncommercial use, providing that such printing is not systematic or excessive;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">stream audio and video files from our website using the media player on our website; and</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">use our marketplace services by means of a web browser,</span></span></span></li>
                </ul>
                </li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">subject to the other provisions of these general terms and conditions.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Except as expressly permitted by provisions of these general terms and conditions, you must not download any material from our website or save any such material to your computer.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You may only use our website for your personal and business purposes in respect of selling or purchasing products on the marketplace.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Except as expressly permitted by these general terms and conditions, you must not edit or otherwise modify any material on our website.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Unless you own or control the relevant rights in the material, you must not:</span></span></span>
                <ul>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">republish material from our website (including republication on another website);</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">sell, rent, or sub-license material from our website;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">show any material from our website in public;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">exploit material from our website for a commercial purpose; or</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">redistribute material from our website.</span></span></span></li>
                </ul>
                </li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You may forward links to products on our website and redistribute our newsletter and promotional materials in print and electronic form to any person.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We reserve the right to suspend or restrict access to our website, to areas of our website, and/or to functionality upon our website. We may, for example, suspend access to the website during server maintenance or when we update the website. You must not circumvent or bypass, or attempt to circumvent or bypass, any access restriction measures on the website.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You must not:</span></span></span>
                <ul>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">use our website in any way or take any action that causes, or may cause, damage to the website or impairment of the performance, availability, accessibility, integrity, or security of the website;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">use our website in any way that is unethical, unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent, or harmful purpose or activity;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">hack or otherwise tamper with our website;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">probe, scan, or test the vulnerability of our website without our permission;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">circumvent any authentication or security systems or processes on or relating to our website;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">use our website to copy, store, host, transmit, send, use, publish or distribute any material which consists of (or is linked to) any spyware, computer virus, Trojan horse, worm, keystroke logger, rootkit, or other malicious computer software;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">impose an unreasonably large load on our website resources (including bandwidth, storage capacity, and processing capacity);</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">decrypt or decipher any communications sent by or to our website without our permission;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">conduct any systematic or automated data collection activities (including without limitation scraping, data mining, data extraction, and data harvesting) on or in relation to our website without our express written consent;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">access or otherwise interact with our website using any robot, spider, or other automated means, except for the purpose of search engine indexing;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">use our website except by means of our public interfaces;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">violate the directives set out in the robots.txt file for our website;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">use data collected from our website for any direct marketing activity (including without limitation email marketing, SMS marketing, telemarketing, and direct mailing); or</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">do anything that interferes with the normal use of our website.</span></span></span></li>
                </ul>
                </li>
            </ol>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Data Privacy</strong></span></span></span></h2>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Buyers agree to the processing of their personal data in accordance with the terms of Xparts.africa&rsquo;s Privacy and Cookie Notice</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Xparts.africa shall process all personal data obtained through the marketplace and related services in accordance with the terms of our Privacy and Cookie Notice and Privacy Policy.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Sellers shall be directly responsible to buyers for any misuse of their personal data, and Xparts.africa shall bear no liability to buyers in respect of any misuse by sellers of their personal data.</span></span></span></li>
            </ol>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Due diligence and audit rights</strong></span></span></span></h2>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We operate an anti-money laundering compliance program and reserve the right to perform due diligence checks on all users of the marketplace.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You agree to provide to us all such information, documentation, and access to your business premises as we may require:</span></span></span>
                <ul>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">in order to verify your adherence to, and performance of, your obligations under this Agreement;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">for the purpose of disclosures pursuant to a valid order by a court or other governmental body; or</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">as otherwise required by law or applicable regulation</span></span></span></li>
                </ul>
                </li>
            </ol>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Xparts.africa&rsquo;s role as a marketplace</strong></span></span></span></h2>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You acknowledge that:</span></span></span>
            
                <ul>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">we do not confirm the identity of all marketplace users, check their creditworthiness or bona fides, or otherwise vet them;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">we do not check, audit, or monitor all information contained in listings;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">we are not a party to any contract for the sale or purchase of products advertised on the marketplace;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">we are not involved in any transaction between a buyer and a seller in any way, save that we facilitate a marketplace for buyers and sellers and process payments on behalf of sellers;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">we are not the agents for any buyer or seller</span></span></span></li>
                </ul>
                </li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">and accordingly, we will not be liable to any person in relation to the offer for sale, sale, or purchase of any car parts products advertised on our marketplace; furthermore, we are not responsible for the enforcement of any contractual obligations arising out of a contract for the sale or purchase of any products and we will have no obligation to mediate between the parties to any such contract.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We do not warrant or represent:</span></span></span>
                <ul>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">the completeness or accuracy of the information published on our marketplace;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">that the material on the marketplace is up to date;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">that the marketplace will operate without fault; or</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">that the marketplace or any service on the marketplace will remain available.</span></span></span></li>
                </ul>
                </li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We reserve the right to discontinue or alter any or all of our marketplace services and to stop publishing our marketplace at any time at our sole discretion without notice or explanation.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We do not guarantee any commercial results concerning the use of the marketplace.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">To the maximum extent permitted by applicable law, we exclude all representations and warranties relating to the subject matter of these general terms and conditions, our marketplace, and the use of our marketplace.</span></span></span></li>
            </ol>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Limitations and exclusions of liability</strong></span></span></span></h2>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Nothing in these general terms and conditions will:</span></span></span>
            
                <ul>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">limit any liabilities in any way that is not permitted under applicable law; or</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">exclude any liabilities or statutory rights that may not be excluded under applicable law.</span></span></span></li>
                </ul>
                </li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">The limitations and exclusions of liability set out in these general terms and conditions:</span></span></span>
                <ul>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">govern all liabilities arising under these general terms and conditions or relating to the subject matter of these general terms and conditions, including liabilities arising in contract, in tort (including negligence) and for breach of statutory duty, except to the extent expressly provided otherwise in these general terms and conditions</span></span></span></li>
                </ul>
                </li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">In respect of the services offered to you free of charge, we will not be liable to you for any loss or damage of any nature whatsoever.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Our aggregate liability to you in respect of any contract to provide services to you under these general terms and conditions shall not exceed the total amount paid and payable to us under the contract. Each separate transaction on the marketplace shall constitute a separate contract for the purpose of this section.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Notwithstanding the section above, we will not be liable to you for any loss or damage of any nature, including in respect of:</span></span></span>
                <ul>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">any losses occasioned by any interruption or dysfunction to the website;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">any losses arising out of any event or events beyond our reasonable control;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">any business losses, including (without limitation) loss of or damage to profits, income, revenue, use, production, anticipated savings, business, contracts, commercial opportunities, or goodwill;</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">any loss or corruption of any data, database, or software; or</span></span></span></li>
                    <li style="list-style-type:circle"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">any special, indirect, or consequential loss or damage.</span></span></span></li>
                </ul>
                </li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We accept that we have an interest in limiting the personal liability of our officers and employees and, having regard to that interest, you acknowledge that we are a limited liability entity; you agree that you will not bring any claim personally against our officers or employees in respect of any losses you suffer in connection with the marketplace or these general terms and conditions (this will not limit or exclude the liability of the limited liability entity itself for the acts and omissions of our officers and employees).</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Our marketplace includes hyperlinks to other websites owned and operated by third parties; such hyperlinks are not recommendations. We have no control over third-party websites and their contents, and we accept no responsibility for them or for any loss or damage that may arise from your use of them.</span></span></span></li>
            </ol>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Entire Agreement</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">These general terms and conditions and the Xparts Africa codes, policies, and guidelines (and in respect of sellers the seller terms and conditions) shall constitute the entire agreement between you and us in relation to your use of our marketplace and shall supersede all previous agreements between you and us in relation to your use of our marketplace.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Hierarchy</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Should these general terms and conditions, the seller terms and conditions, and the Xparts Africa codes, policies, and guidelines be in conflict, these terms and conditions, the seller terms and conditions, and the Xparts Africa codes, policies, and guidelines shall prevail in the order here stated.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Variation</strong></span></span></span></h2>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We may revise these general terms and conditions, the seller terms and conditions, and the Xparts Africa codes, policies, and guidelines from time to time.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">The revised general terms and conditions shall apply from the date of publication on the marketplace.</span></span></span></li>
            </ol>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Severability</strong></span></span></span></h2>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">If a provision of these general terms and conditions is determined by any court or other competent authority to be unlawful and/or unenforceable, the other provisions will continue in effect.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">If any unlawful and/or unenforceable provision of these general terms and conditions would be lawful or enforceable if part of it were deleted, that part will be deemed to be deleted, and the rest of the provision will continue in effect.</span></span></span></li>
            </ol>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Assignment</strong></span></span></span></h2>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You hereby agree that we may assign, transfer, sub-contract or otherwise deal with our rights and/or obligations under these general terms and conditions.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">You may not without our prior written consent assign, transfer, sub-contract or otherwise, deal with any of your rights and/or obligations under these general terms and conditions.</span></span></span></li>
            </ol>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Third party rights</strong></span></span></span></h2>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">A contract under these general terms and conditions is for our benefit and your benefit and is not intended to benefit or be enforceable by any third party.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">The exercise of the parties rights under a contract under these general terms and conditions is not subject to the consent of any third party.</span></span></span></li>
            </ol>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Law and jurisdiction</strong></span></span></span></h2>
            
            <ol>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">These general terms and conditions shall be governed by and construed in accordance with the laws of the territory.</span></span></span></li>
                <li style="list-style-type:decimal"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Any disputes relating to these general terms and conditions shall be subject to the exclusive jurisdiction of the courts of the territory</span></span></span></li>
            </ol>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Our company details</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">The marketplace is operated by Xparts Africa Limited. We are registered in Nigeria under </span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"><span style="background-color:#ffff00">registration number RC 0000000</span></span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">, and our head office is at 113 Ladipo street, Mushin, Lagos. You can contact us by using our marketplace contact form.</span></span></span></p>
            
            <p style="text-align:justify"><br />
            &nbsp;</p>
            
            <p>&nbsp;</p>
            
            ',
        ]);



        Page::Create([
            'name'                                  => 'Privacy Policy',
            'slug'                                  => 'privacy-policy',
            'excerpt'                               => 'Privacy Policy',
            'description'                           => '<p style="text-align:center"><span style="font-size:26pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Privacy Policy</strong></span></span></span></p>

            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Please read this Privacy Policy carefully as it will help you make informed decisions about sharing your personal information with us.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Introduction</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Xparts.africa is thoroughly committed to protecting the privacy of our site visitors and customers. We fully appreciate and respect the importance of privacy on the Internet. We respect each visitor&#39;s and customer&#39;s right to personal privacy. To this end, we collect and use information throughout our website only as disclosed in this Privacy Policy.</span></span></span></p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">What this Privacy Policy Covers</span></span></span></p>
            
            <ul>
                <li style="list-style-type:disc"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">How we collect information from you</span></span></span></li>
                <li style="list-style-type:disc"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">How we protect customers&#39; information</span></span></span></li>
                <li style="list-style-type:disc"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">How we use the information and share all personal information which you provide when you use our websites</span></span></span></li>
                <li style="list-style-type:disc"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">General information in line with extant laws and regulations.</span></span></span></li>
            </ul>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">This policy does not apply to the practices of third-party agents, or people of which we do not exercise direct control, employment, or management.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Consent</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">By using this site, you have consented to our Privacy Policy and that you have the legal capacity to give consent. Otherwise, you may discontinue and log out at this stage.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Collection of Personally Identifiable Information</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We collect personally identifiable information (including but not limited to email address, name, phone number, physical address, location, photo, banking details (when you make purchases), online identifiers, etc.) from you when you set up a free account with Xparts.africa. </span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"><span style="background-color:#ffff00">While you can browse some sections of our site without being a registered member, certain activities (such as placing an order) do require registration</span></span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">. We do use your contact information to send you offers based on your previous orders and your interests. The information and personal data are as freely provided by you to us using any technology at the material time e.g. JWT, web tokens, etc.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Use of Demographic and Profile Data</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We use personal information to provide the services you request. To the extent we use your personal information to market to you, we will provide you the ability to opt out of such uses.&nbsp;</span></span></span></p>
            
            <p>&nbsp;</p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We use your personal information to resolve disputes; troubleshoot problems; help promote a safe service; collect fees owed; measure consumer interest in our products and services, inform you about online and offline offers, products, services, and updates; customize your experience; detect and protect us against error, fraud, and other criminal activity; enforce our terms and conditions; and as otherwise described to you at the time of collection. In our efforts to continually improve our product and service offerings, we collect and analyze demographic and profile data about our users&#39; activity on our website.&nbsp;</span></span></span></p>
            
            <p>&nbsp;</p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We identify and use your IP address to help diagnose problems with our server and to administer our website. Your IP address is also used to help identify you and to gather broad demographic information. We will occasionally ask you to complete optional online surveys. These surveys may ask you for contact information and demographic information (like location, local government area, age, or income level). We use this data to tailor your experience at our site, providing you with content that we think you might be interested in--and to display content according to your preferences.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Cookies</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We use cookies to collect information. A &quot;cookie&quot; is a small piece of information stored by a Web server on a Web browser so it can be later read back from that browser. Cookies are useful for enabling the browser to remember information specific to a given user. Xparts.africa places both permanent and temporary cookies in your computer&#39;s hard drive. Xparts.africa&#39;s cookies do not contain any of your personally identifiable information or private data. We use technology in collecting the information in order to make our Sites and other content or services which we make available to you more interesting and useful.&nbsp;</span></span></span></p>
            
            <p>&nbsp;</p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">For instance, when you come to one of our Sites via your computer or other media device, we may combine your visitor session information or other information collected through cookies, web beacons, and other technical methods with personally identifiable information in order to understand and improve your online experiences and to determine what products, promotions, and services you prefer or are likely to be of interest to you.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Governing Principles of Data Processing</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">a. Your personal data on Xparts.africa shall be collected and processed in accordance with legitimate and lawful purposes consented to by you herein, provided that further processing may be done only for archiving, scientific research, historical research, or statistical purposes for public interest in line with extant regulations and laws.</span></span></span></p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">b. Personal data shall be adequate, accurate, and without prejudice to the dignity of the human person:</span></span></span></p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">c. Personal data shall be stored only for the period within which it is reasonably needed, and shall be secured against all foreseeable hazards and breaches such as theft, cyberattack, viral attack, dissemination, manipulations of any kind, damaged by rain, fire, or exposure to other natural elements.</span></span></span></p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">d. Our data collection shall depict that we owe a duty of care to you.</span></span></span></p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">e. We shall be accountable in line with extant laws and regulations.</span></span></span></p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">6. Sharing of personal information</span></span></span></p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We may share personal information with our other corporate entities and affiliates to help detect and prevent identity theft, fraud, and other potentially illegal acts; correlate related or multiple accounts to prevent abuse of our services; and facilitate joint or co-branded services that you request where such services are provided by more than one corporate entity. Those entities and affiliates may not market to you as a result of such sharing unless you explicitly opt-in.&nbsp;</span></span></span></p>
            
            <p>&nbsp;</p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We may disclose personal information if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal processes. We may disclose personal information to law enforcement offices, third party rights owners, third-party vendors, contractors, and suppliers who perform services for us or on our behalf and require access to such information to do that service, or others in the good faith belief that such disclosure is reasonably necessary to: enforce our Terms or Privacy Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of our users or the general public. Xparts.africa and its affiliates will share some or all of your personal information with another business entity should we (or our assets) plan to merge with, or be acquired by that business entity. Should such a transaction occur, that other business entity (or the new combined entity) will be required to follow this privacy policy with respect to your personal information.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Personal Data Retention Period</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Xparts.africa will only keep your personal information for as long as it is necessary for the purposes set out in this Privacy Policy unless a longer retention period is required or permitted by law (such as tax, accounting, or other legal requirements.)&nbsp;</span></span></span></p>
            
            <p>&nbsp;</p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Upon request for account closure, your account will be closed but this closure will not involve the deletion of historical records of the account for the reasons already stated. However, except as may be required by law or law enforcement agents and/or regulators, further processing of the personal information related to the account will cease from the time of closure.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Your Privacy Rights</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">In certain circumstances as provided under the Nigeria Data Protection Regulation or any other applicable law, you may object to the processing of your personal information or request to delete already inputted personal data. To make this request take the following simple steps:</span></span></span></p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">1. Send an email to </span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"><span style="background-color:#ffff00">help@xparts.africa</span></span></span></span></p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">2. Title your email delete my personal data</span></span></span></p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">3. We will act upon your request in accordance with applicable data protection laws.</span></span></span></p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">With that, it is as simple as done.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Links to Other Sites</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Our site links to other websites that may collect personally identifiable information about you. Xparts.africa is not responsible for the privacy practices or the content of those linked websites.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Security Precautions</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Our site has stringent security measures in place to protect the loss, misuse, and alteration of the information under our control. Whenever you change or access your account information, we offer the use of a secure server. Once your information is in our possession we adhere to strict security guidelines, protecting it against unauthorized access.&nbsp;</span></span></span></p>
            
            <p>&nbsp;</p>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">However, please bear in mind that we cannot guarantee that the internet in itself is 100% secure and so we cannot take responsibility for the illegal acts of hackers as long as we have taken the necessary precautions. Although we will do our best to protect your personal information, the transmission of personal information to and from our services is at your own risk. You should only access our site or services through and within a secure environment. Most importantly, you are responsible for keeping your User ID and password secure and you should not disclose them to anyone.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Choice/Opt-Out</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Xparts.africa provides all users with the opportunity to opt-out of receiving non-essential (promotional, marketing-related) communications from us on behalf of our partners, and from us in general, after setting up an account. If you want to remove your contact information from all Xparts.africa lists and newsletters, </span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"><span style="background-color:#ffff00">please visit https://www.Xparts.africa/unsubscribe</span></span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">. In the future, you can unsubscribe by clicking the one-click unsubscribe button located at the bottom of every email.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><span style="background-color:#ffff00"><strong>Advertisements on Xparts.africa</strong></span></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">We use third-party advertising companies to serve ads when you visit our website. These companies may use information (not including your name, address, email address, or telephone number) about your visits to this and other websites in order to provide advertisements about goods and services of interest to you.</span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Remedies, Questions, and Contact</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">If observe or have good grounds that your privacy rights have been infringed or are likely to be infringed by the use of our Site please lodge your complaints or questions regarding our policy to the following address: </span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"><span style="background-color:#ffff00">help@xparts.africa.</span></span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"> Our Data Protection Officer shall attend to them. Generally, you may contact us on any issue by mail to </span></span></span><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000"><span style="background-color:#ffff00">help@xparts.africa.</span></span></span></span></p>
            
            <h2 style="text-align:justify"><span style="font-size:16pt"><span style="font-family:Georgia"><span style="color:#000000"><strong>Notification of Changes</strong></span></span></span></h2>
            
            <p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Georgia"><span style="color:#000000">Xparts.africa reserves the right to make changes and/or updates to this Privacy Policy from time to time, without prior notice, and the latest version of this policy will be posted on our websites. You are advised to view this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on our web pages.</span></span></span></p>
            
            <p>&nbsp;</p>
            ',
        ]);
    }
}
